import {
  Activity,
  Anchor,
  Archive,
  Atom,
  ChartBar,
  Blocks,
  Box,
  Boxes,
  Bug,
  Circle,
  Clock,
  Cloud,
  Copy,
  Cpu,
  Database,
  DatabaseZap,
  FileCode,
  FileCog,
  FileText,
  FingerprintPattern,
  Flame,
  Folder,
  FolderArchive,
  GitBranch,
  GitMerge,
  HardDrive,
  Hexagon,
  Key,
  Layers,
  Lock,
  Network,
  Package,
  Palette,
  Plug,
  Rocket,
  Route,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Signpost,
  SquareCheck,
  SquareTerminal,
  Terminal,
  TrendingUp,
  UserCheck,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { GithubIcon } from "./BrandIcons";

export const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  archive: Archive,
  atom: Atom,
  "chart-bar": ChartBar,
  blocks: Blocks,
  box: Box,
  boxes: Boxes,
  bug: Bug,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "database-zap": DatabaseZap,
  "file-code": FileCode,
  "file-cog": FileCog,
  "file-text": FileText,
  "fingerprint-pattern": FingerprintPattern,
  flame: Flame,
  folder: Folder,
  "folder-archive": FolderArchive,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  github: GithubIcon as unknown as LucideIcon,
  "hard-drive": HardDrive,
  hexagon: Hexagon,
  key: Key,
  layers: Layers,
  lock: Lock,
  network: Network,
  package: Package,
  palette: Palette,
  plug: Plug,
  rocket: Rocket,
  route: Route,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  signpost: Signpost,
  "square-check": SquareCheck,
  "square-terminal": SquareTerminal,
  terminal: Terminal,
  "trending-up": TrendingUp,
  "user-check": UserCheck,
  workflow: Workflow,
};
